variable "vpc_name" {}
variable "vpc_cidr" {}
variable "igw_name" {}
variable "public_subnet1_name" {}
variable "public_subnet1_cidr" {}
variable "route_table_public_subnet1_name" {}
variable "region" {}
variable "ami" {}
variable "instance_type" {}
variable "public_cidr_block" {}